### ISSUE TITLE
Look into loading screen / animation for initial connection?

### ISSUE THREAD

**Issue by DootLord** [HarryW96/INSE_Development#7]
Loading times are very long as everything seems to be an image.

Took 21 secs on first connection!

**Comment by DootLord** [comment]
**Unnecessary**. Will have a somewhat long development time to implement, and will give the project little extra value.

**Comment by DootLord** [comment]
Replace all empty elements with the text "loading..." Gives it a good aesthetics as apposed to empty boxes.

**Comment by HarryW96** [comment]
Could just set the pages opacity to 0 for a limit of 10 seconds and then have a CSS animation on top like a loading bar and then swap the opacity so it fades in the full page again once fully loaded? Wouldn't take long at all and I can handle this!

**Comment by HarryW96** [comment]
Tried attempting this but is gonna be a much bigger pain in the arse than originally thought because foundation is annoying and only likes its own stuff and css most of the time. Will look into it more and properly if have time and nothing else to work on. Also due to minify of images load time is much more minimal than it was originally so may not be needed.

**Comment by DootLord** [comment]
Not to worry. Make this the lowest property task though, as other issues are much more important currently.

If we have extra time we can use the animate.css file I implemented a few commits ago to flash things up a bit.

**Comment by HarryW96** [comment]
No worries mate can do.

**Comment by DootLord** [comment]
No animation, but html elements are set to "loading..." when waiting for API updates.

Good enough!!
